# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_remove_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
