# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_useritem_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
